--VIEW DATA--
SELECT * FROM HOUSINGDATA

--POPULATE ADDRESS DATA IE ANY PARCELID THAT IS SIMILAR SHOULD HAVE SAME ADDRESS AND NOT NULL FOR SOME--
SELECT A.UniqueID, A.ParcelID, A.PropertyAddress, B.UniqueID, B.ParcelID, B.PropertyAddress, ISNULL(A.PropertyAddress, B.PropertyAddress)
FROM HOUSINGDATA A
JOIN HOUSINGDATA B
ON A.ParcelID = B.ParcelID
WHERE A.PropertyAddress IS NULL

UPDATE A
SET PropertyAddress = 
ISNULL(A.PropertyAddress, B.PropertyAddress)
FROM HOUSINGDATA A
JOIN HOUSINGDATA B
ON A.ParcelID = B.ParcelID
WHERE A.PropertyAddress IS NULL

--BREAKOUT ADDRESS INTO INDIVIDUAL COLUMNS--
SELECT PARSENAME(REPLACE(PropertyAddress, ',', '.'), 2) AS ADDRESS,
       PARSENAME(REPLACE(PropertyAddress, ',', '.'), 1) AS STREETNAME
FROM HOUSINGDATA

--ADD INDIVIDUAL COLUMNS TO TABLE--
ALTER TABLE HOUSINGDATA
ADD ADDRESS VARCHAR(50)

ALTER TABLE HOUSINGDATA
ADD STREETNAME VARCHAR(50)

UPDATE HOUSINGDATA
SET ADDRESS = PARSENAME(REPLACE(PropertyAddress, ',', '.'), 2)

UPDATE HOUSINGDATA
SET STREETNAME = PARSENAME(REPLACE(PropertyAddress, ',', '.'), 1)

--BREAKOUT ADDRESS INTO INDIVIDUAL COLUMNS--
SELECT PARSENAME(REPLACE(OwnerAddress, ',', '.'), 3) AS OWNERADDRESS,
       PARSENAME(REPLACE(OwnerAddress, ',', '.'), 1) AS STREET,
	   PARSENAME(REPLACE(OwnerAddress, ',', '.'), 1) AS STATE
FROM HOUSINGDATA

--ADD INDIVIDUAL COLUMNS TO TABLE--
ALTER TABLE HOUSINGDATA
ADD OWNERSADDRESS VARCHAR(50)

ALTER TABLE HOUSINGDATA
ADD STREET VARCHAR(50)

ALTER TABLE HOUSINGDATA
ADD STATE VARCHAR(50)

UPDATE HOUSINGDATA
SET OWNERSADDRESS = PARSENAME(REPLACE(PropertyAddress, ',', '.'), 3)

UPDATE HOUSINGDATA
SET STREET = PARSENAME(REPLACE(PropertyAddress, ',', '.'), 2)

UPDATE HOUSINGDATA
SET STATE = PARSENAME(REPLACE(PropertyAddress, ',', '.'), 1)

--CHANGE 1 AND 0 TO YES AND NO IN 'SOLD AS VACANT'--
SELECT SoldAsVacant,
 CASE WHEN SoldAsVacant = 0 THEN 'NO'
 ELSE 'YES'
 END AS SoldAsVacant
FROM HOUSINGDATA

ALTER TABLE HOUSINGDATA
ADD SOLDHOUSES VARCHAR(50)

UPDATE HOUSINGDATA
SET SOLDHOUSES = CASE WHEN SoldAsVacant = 0 THEN 'NO'
 ELSE 'YES'
 END 

--DELETE UNUSED COLUMNS/ UPDATE--
SELECT * FROM HOUSINGDATA

ALTER TABLE HOUSINGDATA
DROP COLUMN PropertyAddress, OWNERSADDRESS, SoldAsVacant


